---

- name: Create Expensify User
  user:
    name: expensify
    shell: /bin/bash
    groups: sudo
    append: yes
    create_home: yes

- name: Create .ssh directory
  file:
    state: directory
    path: /home/expensify/.ssh
    owner: expensify
    group: expensify
    mode: 0755 

- name: Copy Authorized Keys file
  copy:
    src: infra_team_authorized_keys
    dest: /home/expensify/.ssh/authorized_keys
    owner: expensify
    group: expensify
    mode: 0600

- name: Setting SSH Allow Rule
  ufw:
    rule: accept
    port: ssh
    proto: tcp
    from_ip: "{{ item }}"
  loop: groups['nagios']
  when: "'monitorred_group' in group_names"

- name: Setting SSH Deny any rule
  ufw:
    rule: reject
    port: ssh
    proto: tcp
    insert: 997
  when: "'monitorred_group' in group_names"

- name: Setting HTTP Allow Rule
  ufw:
    rule: accept
    port: http
    proto: tcp
  when: ("'webservers' in group_names") or ("'nagios' in group_names")

- name: Setting Port Range Allow Rule
  ufw:
    rule: accept
    port: 60000:65000
    proto: tcp
  when: "'loadbalancer' in group_names"

- name: Setting Public SSH Allow Rule
  ufw:
    rule: accept
    port: ssh
    proto: tcp
    from_ip: any
  when: "'nagios' in group_names"

- name: Deny Everything Else
  ufw:
    rule: deny
    port: any
    proto: any
    from_ip: any