---
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  inventory:
    group_vars:
      a:
        StringValue: A
      b:
        StringValue: B
  env:
    ANSIBLE_ROLES_PATH: "../.."
platforms:
  - hostname: 52.11.201.248
    name: 52.11.201.248
    box: bento/ubuntu-24.04
    memory: 512
    cpus: 1
    groups:
      - monitorred_group
      - webservers
      - a
  - hostname: 54.245.12.202
    name: 54.245.12.202
    box: bento/ubuntu-24.04
    memory: 512
    cpus: 1
    groups:
      - monitorred_group
      - webservers
      - b