---
- name: Install Dependency Packages for Nagios
  apt:
    state: present
    update_cache: yes
    pkg:
     - autoconf
     - bc
     - gawk
     - dc
     - build-essential
     - gcc
     - libc6
     - wget
     - unzip
     - apache2
     - php
     - libapache2-mod-php
     - libgd-dev
     - libmcrypt-dev
     - make
     - libssl-dev
     - snmp
     - libnet-snmp-perl
     - gettext
     - python3-passlib

- name: Get and Untar Nagios
  unarchive:
    src: "https://github.com/NagiosEnterprises/nagioscore/releases/download/nagios-{{ nagios_version }}/nagios-{{ nagios_version }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Run Configure
  command: ./configure --with-httpd-conf=/etc/apache2/sites-enabled
  args:
    chdir: "/tmp/nagios-{{ nagios_version }}"

- name: Run Make All
  make:
    chdir: "/tmp/nagios-{{ nagios_version }}"
    target: all

- name: Run Make Install Groups Users
  make:
    chdir: "/tmp/nagios-{{ nagios_version }}"
    target: install-groups-users

- name: Add Nagios User to www-data
  user:
    name: nagios
    groups: www-data
    append: yes
  notify: 
    - Restart Apache
    - Restart Nagios

- name: Run Make Install
  make:
    chdir: "/tmp/nagios-{{ nagios_version }}"
    target: "{{ item }}"
  loop:
    - install
    - install-daemoninit
    - install-commandmode
    - install-config
    - install-webconf
  notify: 
    - Restart Apache
    - Restart Nagios

- name: Enable Apache Mods
  apache2_module:
    state: present
    name: "{{ item }}"
  loop:
    - rewrite
    - cgi
  notify: 
    - Restart Apache
    - Restart Nagios

- name: Set htpasswd
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: "{{ nagios_password }}"
  notify: 
    - Restart Apache
    - Restart Nagios

- name: Set Permissions for Nagios RW Directory
  command: chmod ugo+rw /usr/local/nagios/var/rw/ /usr/local/nagios/var/rw/nagios.cmd

- name: Install NRPE Plugin
  apt:
    state: present
    pkg: 
      - nagios-nrpe-plugin
      - nagios-plugins-contrib
      - monitoring-plugins

- name: Create Directory
  file:
    state: directory
    owner: nagios
    group: nagios
    mode: '0775'
    path: /usr/local/nagios/etc/servers

- name: Copy Edited Nagios Config
  copy:
    src: nagios.cfg
    dest: /usr/local/nagios/etc/nagios.cfg
    owner: nagios
    group: nagios
    mode: '0664'
  notify: 
    - Restart Nagios

- name: Copy Edited Resource Config
  copy:
    src: resource.cfg
    dest: /usr/local/nagios/etc/resource.cfg
    owner: nagios
    group: nagios
    mode: '0660'
  notify: 
    - Restart Nagios

- name: Copy Edited Commands Config
  copy:
    src: "{{ item }}"
    dest: "/usr/local/nagios/etc/objects/{{ item }}"
    owner: nagios
    group: nagios
    mode: '0664'
  loop:
    - commands.cfg
    - localhost.cfg
  notify: 
    - Restart Nagios