---
- name: Configure Nagios to monitor all servers
  hosts: nagios
  remote_user: ubuntu
  become: true

  roles:
    - role: nagios-server
      tags:
        - Nag-Server
    - role: custom-nagios-plugin
      tags:
        - Nag-Server

- name: Install NRPE on Remote Servers
  hosts: 
    - webservers
    - loadbalancer
  remote_user: ubuntu
  become: true

  roles:
    - role: nrpe-clients
      tags:
        - Nag-Clients

- name: Push out the Client Configs
  hosts: nagios
  remote_user: ubuntu
  become: true

  roles:
    - role: nagios-client-config
      tags:
        - Nag-Server